version: '3'

services:
    php:
        image: webdevops/php-nginx-dev:7.4
        volumes:
            - ./:/app
            - ~/.ssh:/home/application/.ssh
        working_dir: /app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            WEB_DOCUMENT_INDEX: index.php
            PHP_MAX_EXECUTION_TIME: 3600
            PHP_DISPLAY_ERRORS: 1
            COMPOSER_MEMORY_LIMIT: -1
            DOMAIN_NAME: ${DOMAIN_NAME}
            VIRTUAL_HOST: ${DOMAIN_NAME}
            APPLICATION_UID: shell id -u
            APPLICATION_GID: shell id -g
            PHP_DEBUGGER: xdebug
            XDEBUG_REMOTE_AUTOSTART: 1
            COMPOSER_VERSION: 2
        ports:
            - ${ENGINE_PORT}:80
        depends_on:
            - database
        networks:
            - appnet

    database:
        image: postgres:13
        volumes:
            - ./docker/postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${ROOT_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - 5439:5432
        networks:
            - appnet
    cron:
        container_name: cron
        build: docker/cron/
        restart: always
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - appnet
        depends_on:
            - php

networks:
    appnet:
        driver: "bridge"

volumes:
    mysql_data:
        driver: "local"
