version: '2'

services:
    mysql:
        container_name: mysql
        build: docker/mysql
        ports:
            - 3308:3306
        restart: always
        #privileged: true
        volumes:
            - ./docker/data/mysql:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: student
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        networks:
            - app
        user: root
    php:
        container_name: php
        build: docker/php/
        ports:
            - 9001:9000
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - /etc/timezone:/etc/timezone:cached
        networks:
            - app
    nginx:
        container_name: nginx
        build: docker/nginx/
        ports:
            - 82:80
        restart: always
        volumes_from:
            - php
        networks:
            - app
    cron:
        container_name: cron
        build: docker/cron/
        restart: always
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - app
        depends_on:
            - php
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8088:8080

networks:
    app:
        driver: bridge

volumes:
    data:
        driver: local
