FROM debian:jessie

RUN apt-get update && \
    apt-get -y install apt-transport-https \
         ca-certificates \
         curl \
         cron \
         gnupg2 \
         supervisor \
         software-properties-common && \
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
    add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
       $(lsb_release -cs) \
       stable" && \
    apt-get update && \
    apt-get -y install docker-ce

COPY supervisord.conf /etc/supervisor/conf.d/supervisor.conf
COPY crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab

CMD ["/usr/bin/supervisord"]